# Generated by Django 5.0.3 on 2024-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_options_comment_active_comment_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.comment'),
        ),
    ]
