# Generated by Django 5.0.3 on 2024-03-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
